### ISSUE TITLE
Division by zero warning from pyrealm

### ISSUE THREAD

**Issue by hrlai** [ImperialCollegeLondon/virtual_rainforest#1078]
**Describe the bug**
This is not really a bug but to understanding a warning behaviour. When running ve_example I get the following warning message (only showing part of the console output), is it safe to ignore?

```
Starting Virtual Ecosystem simulation.
Logging to: ve_example\out\ve_example.log
* Loading configuration
* Saved compiled configuration: ve_example\out\ve_full_model_configuration.toml
* Built core model components
* Initial data loaded
* Models initialised: animal, plants, soil, hydrology, abiotic_simple, litter
* Saved model initial state
* Starting simulation
  0%|                                          | 0/24 [00:00<?, ?it/s]pyrealm\plants_model.py:971: RuntimeWarning: invalid value encountered in divide
pyrealm\losses.py:341: RuntimeWarning: divide by zero encountered in divide
pyrealm\losses.py:397: RuntimeWarning: divide by zero encountered in divide
  4%|█▍                                | 1/24 [00:03<01:22,  3.57s/it]pyrealm\plants_model.py:974: RuntimeWarning: invalid value encountered in divide
pyrealm\losses.py:341: RuntimeWarning: divide by zero encountered in divide
pyrealm\losses.py:397: RuntimeWarning: divide by zero encountered in divide
  8%|██▊                               | 2/24 [00:07<01:20,  3.67s/it]pyrealm\plants_model.py:974: RuntimeWarning: invalid value encountered in divide
pyrealm\losses.py:341: RuntimeWarning: divide by zero encountered in divide
pyrealm\losses.py:397: RuntimeWarning: divide by zero encountered in divide
 12%|████▎                             | 3/24 [00:10<01:16,  3.66s/it]pyrealm\plants_model.py:974: RuntimeWarning: invalid value encountered in divide
pyrealm\losses.py:341: RuntimeWarning: divide by zero encountered in divide
pyrealm\losses.py:397: RuntimeWarning: divide by zero encountered in divide
 17%|█████▋                            | 4/24 [00:14<01:14,  3.74s/it]pyrealm\plants_model.py:974: RuntimeWarning: invalid value encountered in divide
pyrealm\losses.py:341: RuntimeWarning: divide by zero encountered in divide
pyrealm\losses.py:397: RuntimeWarning: divide by zero encountered in divide
 21%|███████                           | 5/24 [00:18<01:13,  3.85s/it]pyrealm\plants_model.py:974: RuntimeWarning: invalid value encountered in divide
pyrealm\losses.py:341: RuntimeWarning: divide by zero encountered in divide
pyrealm\losses.py:397: RuntimeWarning: divide by zero encountered in divide
 25%|████████▌                         | 6/24 [00:23<01:11,  3.99s/it]
```

**To Reproduce**
Run `ve_run ./ve_example/config -o ./ve_example/out --logfile ./ve_example/out/ve_example.log`

**Desktop:**

- OS: Microsoft Windows 11
- Version 10.0.22631 N/A Build 22631
- ve_run 0.1.1a13

**Comment by davidorme** [comment]
Those are definitely things we need to fix so an issue is appropriate! I had been meaning to add the same thing myself.

**Comment by jacobcook1995** [comment]
I *think* this one was fixed by #1006

**Comment by davidorme** [comment]
Yeah - I thought I'd seen that. The one in the `plants_model` isn't fixed though. Plus `pyrealm` is hijacking the warning formats...

**Comment by hrlai** [comment]
I have not been seeing this message for awhile now, so closing it.
